version: '3'
services:
  flyway:
    network_mode: host
    image: flyway/flyway
    command: -url=jdbc:postgresql://localhost:5432/postgres -schemas=test -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./schema:/flyway/sql