version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - local

networks:
  local: